apiVersion: v1
kind: Namespace
metadata:
  name: ai-warehouse
  labels:
    name: ai-warehouse
    environment: ${ENV}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
  labels:
    name: ai-platform
    environment: ${ENV}
---
apiVersion: v1
kind: Namespace
metadata:
  name: manufacturing
  labels:
    name: manufacturing
    environment: ${ENV}
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: ${ENV}
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    name: storage
    environment: ${ENV}
